import React, { useContext } from 'react';
import diet from '../assets/diet-7610151_1280.png';
import exercise from '../assets/exercise.png';
import ai from '../assets/ai.png';
import { AppContext } from '../context/AppContext';

const About = () => {
  const { setOpenLogin } = useContext(AppContext);

  return (
    <div className=" about-section w-full min-h-screen flex flex-col items-center bg-gradient-to-b from-gray-950 to-sky-900 text-white" data-section="about" id='about' >
      <div className="w-10/12 p-5">
        <h1 className="text-center text-[40px] sm:text-[50px] md:text-[60px] custom-text mt-6">
          About Us
        </h1>
        <p className="text-[20px] sm:text-[22px] md:text-[25px] font-semibold mt-4 text-blue-200">
          We are committed to helping you to achieve your fitness goals.
        </p>
        <p className="text-[13px] sm:text-[16px] md:text-[20px] mt-3 italic">
          Fitify is a platform dedicated to providing personalized diet plans and workout routines. Our mission is to empower individuals to lead healthier lives through AI guidance and support.
        </p>
        <button
          className="bg-orange-400 text-center font-bold rounded-md mx-2 p-2 w-4/12 md:w-[95px] uppercase mt-2 hover:scale-110 transition-all duration-300 shadow-md shadow-orange-700"
          onClick={() => setOpenLogin(true)}
        >
          Explore !
        </button>
      </div>

      <div className="flex flex-col justify-center items-center w-full md:flex-row md:items-stretch md:gap-4">
        <div className="bg-blue-300 py-6 px-8 my-4 text-center rounded-md w-10/12 md:w-3/12 mx-2 shadow-md shadow-black hover:scale-105 transition-all duration-500">
          <div className="flex flex-col gap-1 justify-center items-center">
            <img src={diet} className="w-[50px] text-blue-900" />
            <h1 className="text-lg sm:text-xl font-semibold text-gray-800 mt-3">AI Generated Diet Plan</h1>
          </div>
          <p className="text-md mt-2 text-black">
            Get customized diet plans tailored to your specific needs and goals, generated by Google Gemini.
          </p>
        </div>
        <div className="bg-blue-300 py-6 px-8 my-4 text-center rounded-md w-10/12 md:w-3/12 mx-2 shadow-md shadow-black hover:scale-105 transition-all duration-500">
          <div className="flex flex-col gap-1 justify-center items-center">
            <img src={exercise} className="w-[150px] text-blue-900" />
            <h1 className="text-lg sm:text-xl font-semibold text-gray-800">Exercises</h1>
          </div>
          <p className="text-md mt-2 text-black">
            Discover a variety of exercises designed to enhance your fitness routine and help you achieve your health goals.
          </p>
        </div>
        <div className="bg-blue-300 py-6 px-8 my-4 text-center rounded-md w-10/12 md:w-3/12 mx-2 shadow-md shadow-black hover:scale-105 transition-all duration-500">
          <div className="flex flex-col gap-1 justify-center items-center">
            <img src={ai} className="w-[80px] text-blue-900" />
            <h1 className="text-lg sm:text-xl font-semibold text-gray-800">Ask AI</h1>
          </div>
          <p className="text-md mt-2 text-black">
            Have any fitness-related questions? Our AI assistant is here to provide you with the answers you need.
          </p>
        </div>
      </div>
    </div>
  );
};

export default About;
